version: '3'

services:
  backend:
    build: ./backend
    ports:
      - "5001:5001"
    depends_on:
      - mariadb

  mariadb:
    image: mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
