version: '3'

services:
  mariadb:
    image: mariadb
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: app_db
      TZ: Asia/Tokyo
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test:
        [
          "CMD",
          "healthcheck.sh",
          "--su-mysql",
          "--connect",
          "--innodb_initialized"
        ]
      interval: 3s
      timeout: 10s
      retries: 3

  app:
    build: ./app
    ports:
      - "5001:5001"
    depends_on:
      mariadb:
        condition: service_healthy
    environment:
      DEV: "true"
      CLIENT_ID: "${CLIENT_ID}"
      CLIENT_SECRET: "${CLIENT_SECRET}"
      REDIRECT_URI: "${REDIRECT_URI}"
      AUTHORIZE_URL: "${AUTHORIZE_URL}"
      TOKEN_URL: "${TOKEN_URL}"
      DEV_USER: "${DEV_USER}"

    volumes:
      - ./app:/app  


  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: mariadb

volumes:
  mariadb_data:
