version: '3'

services:
  backend:
    build: ./backend
    ports:
      - "5001:5001"
    depends_on:
      - mariadb

  mariadb:
    image: mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app_db
      MYSQL_USER: root 
      MYSQL_PASSWORD: password
      TZ: Asia/Tokyo
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --init-file /docker-entrypoint-initdb.d/init.sql

volumes:
  mariadb_data:
